import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const sourcePath = resolve(
  "node_modules/zxing-wasm/dist/reader/zxing_reader.wasm",
);
const outputPath = resolve("receive/zxing-wasm-inline.generated.ts");
const wasmBase64 = readFileSync(sourcePath).toString("base64");
const generatedSource = `// Generated by scripts/generate_inline_wasm.mjs. Do not edit manually.
export const zxingWasmDataUrl = "data:application/wasm;base64,${wasmBase64}";
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, generatedSource);

console.log(JSON.stringify({
  sourcePath,
  outputPath,
  wasmBytes: Buffer.byteLength(wasmBase64, "base64"),
  generatedBytes: Buffer.byteLength(generatedSource),
}));
